---
- name: Install Apache
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Configure Apache
  ansible.builtin.template:
    src: apache.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify: restart apache

- name: Deploy default webpage
  ansible.builtin.copy:
    src: default.html
    dest: /var/www/html/index.html
